name: Node CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update ke v4 sekalian biar makin stabil

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # Tambahkan cache supaya install lebih cepat

      - name: Install dependencies
        run: npm install

      # --- TAMBAHKAN LANGKAH INI ---
      - name: Fix Permissions
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Test
        run: npm test